
export const REQUEST = "REQUEST"
export const FAILURE = "FAILURE"
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS"
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS"

export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS"
